"""Booking confirmation / invoice emails.

Sends an auto-generated HTML invoice after a LIVE flight redemption. SMTP is
configured entirely from the environment so no secret ever lives in code:

    SMTP_HOST   (default smtp.gmail.com)
    SMTP_PORT   (default 587, STARTTLS)
    SMTP_USER   (the sending account, e.g. a Gmail address)
    SMTP_PASS   (an app password — NOT the account password)
    EMAIL_FROM  (optional display From:, defaults to SMTP_USER)
    BOOKING_EMAIL_TO (default recipient for booking invoices)

Unconfigured (no SMTP_USER/SMTP_PASS) → send() logs and returns False; the
booking itself is never blocked or rolled back by an email problem.
"""

from __future__ import annotations

import asyncio
import logging
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

log = logging.getLogger(__name__)

DEFAULT_BOOKING_EMAIL_TO = "samyakrao31@gmail.com"


def is_configured() -> bool:
    return bool(os.getenv("SMTP_USER") and os.getenv("SMTP_PASS"))


def booking_recipient() -> str:
    return os.getenv("BOOKING_EMAIL_TO", DEFAULT_BOOKING_EMAIL_TO)


def _fmt_inr(v: float | int | None) -> str:
    try:
        return f"₹{float(v):,.0f}"
    except (TypeError, ValueError):
        return "—"


def build_flight_invoice_html(order: dict) -> str:
    """Self-contained HTML invoice — every figure comes from the completed
    redemption record, never invented here."""
    rows = "".join(
        f"<tr><td style='padding:6px 14px;color:#5b6472'>{k}</td>"
        f"<td style='padding:6px 14px;font-weight:600;color:#101828;text-align:right'>{v}</td></tr>"
        for k, v in [
            ("Booking reference (PNR)", order.get("booking_reference") or "—"),
            ("Airline", order.get("airline") or "—"),
            ("Route", f"{order.get('origin', '?')} → {order.get('destination', '?')}"),
            ("Departure", order.get("departing_at") or order.get("depart_date") or "—"),
            ("Travellers", order.get("passengers") or 1),
            ("Cabin", (order.get("cabin") or "economy").replace("_", " ").title()),
            ("Points redeemed", f"{int(order.get('points_used') or 0):,} pts"),
            ("Cash equivalent", _fmt_inr(order.get("cash_price_inr"))),
            ("Cash paid", _fmt_inr(order.get("cash_due_inr") or 0)),
            ("Card", order.get("card_name") or "—"),
            ("Points balance after", f"{int(order.get('balance_after') or 0):,} pts"),
            ("Transaction id", order.get("transaction_id") or "—"),
            ("Booked at", datetime.now().strftime("%d %b %Y, %H:%M")),
        ]
    )
    return f"""\
<div style="font-family:Segoe UI,Arial,sans-serif;max-width:560px;margin:0 auto;border:1px solid #e4e9f0;border-radius:14px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#123B6B,#0C2748);color:#fff;padding:22px 26px">
    <div style="font-size:19px;font-weight:800">CredArt Rewards — Booking confirmed ✈️</div>
    <div style="font-size:13px;opacity:.85;margin-top:4px">Your flight was booked with points. This is your invoice.</div>
  </div>
  <table style="width:100%;border-collapse:collapse;font-size:14px;margin:12px 0">{rows}</table>
  <div style="padding:14px 26px 20px;font-size:12px;color:#8a93a3;border-top:1px solid #eef1f6">
    Auto-generated by the CredArt travel concierge. Booked via the Duffel test environment —
    a real order record with a real airline booking reference; no payment card was charged.
  </div>
</div>"""


def _send_sync(to: str, subject: str, html: str) -> bool:
    host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    port = int(os.getenv("SMTP_PORT", "587"))
    user = os.getenv("SMTP_USER", "")
    # Google displays app passwords as "xxxx xxxx xxxx xxxx" — accept either form
    password = os.getenv("SMTP_PASS", "").replace(" ", "")
    sender = os.getenv("EMAIL_FROM", user)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"CredArt Rewards <{sender}>"
    msg["To"] = to
    msg.attach(MIMEText(html, "html", "utf-8"))

    with smtplib.SMTP(host, port, timeout=20) as smtp:
        smtp.starttls()
        smtp.login(user, password)
        smtp.sendmail(sender, [to], msg.as_string())
    return True


async def send_flight_invoice(order: dict, to: str | None = None) -> bool:
    """Best-effort: True if the invoice email went out, False otherwise."""
    recipient = to or booking_recipient()
    if not is_configured():
        log.warning("email not configured (set SMTP_USER/SMTP_PASS) — skipping invoice to %s", recipient)
        return False
    subject = (f"CredArt booking confirmed — {order.get('airline', 'flight')} "
               f"{order.get('origin', '')}→{order.get('destination', '')} · PNR {order.get('booking_reference', '')}")
    try:
        return await asyncio.to_thread(_send_sync, recipient, subject, build_flight_invoice_html(order))
    except Exception as exc:  # noqa: BLE001 — email must never break a booking
        log.error("invoice email to %s failed: %s", recipient, exc)
        return False
